* cursorfree.el
A GNU Emacs package for editing text from any position in the buffer.

This package provides a library and command language well suited for
voice control of Emacs.  This allows you to modify text, jump around
in the buffer and follow links by referring to the exact target of
your action immediately.

This package was inspired by [[https://github.com/cursorless-dev/cursorless/][cursorless]], a package providing similar
faculties for VSCode.

** Setup
*** Required dependencies
If you intend to use this with voice control, install [[https://github.com/ErikPrantare/phony.el][phony.el]] (unless
you plan to design your own grammar).

*** Recommended dependencies
- [[https://github.com/ErikPrantare/hatty.el][hatty.el]] for a way to query arbitrary positions in the visible
  buffer text.
- [[https://github.com/magnars/multiple-cursors.el][multiple-cursors.el]] for integration with multiple-cursors.  Useful
  when working with multiple targes at once.

*** Installation
Clone this repository and add the following to your init file:

#+begin_src elisp
  (add-to-list 'load-path "path/to/cursorfree/directory")
  (require 'cursorfree)
#+end_src

*** Talon integration

#+begin_src elisp
  (phony-define-dictionary hatty-color
    :external-name "color"
    '(("yellow" . yellow)
      ("red" . red)
      ("blue" .  blue)
      ("pink" . pink)
      ("green" . green)))

  (phony-define-dictionary hatty-shape
    :external-name "hat_shape"
    '(("bolt" . bolt)
      ("curve" . curve)
      ("fox" . fox)
      ("frame" . frame)
      ("play" . play)
      ("wing" . wing)
      ("hole" . hole)
      ("ex" . ex)
      ("cross" . cross)
      ("eye" . eye)))

  (phony-define-dictionary my/actions
    :external-name "cursorfree_action"
    cursorfree-actions)

  (phony-define-dictionary my/modifiers
    :external-name "cursorfree_modifier"
    cursorfree-modifiers)
#+end_src

Then, copy [[file:talon/cursorfree.py][talon/cursorfree.py]] to your talon configuration.  It is
assumed you have a rule ~<user.any_alphanumeric_key>~, as provided by
the community configuration.

After this, add the following as a spoken rule to your talon
configuration:

#+begin_src talon
  <user.cursorfree_command>:
      user.emacs_lisp("(with-selected-window {window} (cursorfree-evaluate {cursorfree_command}))")
#+end_src

** Usage
A cursorfree command corresponds to a sequence of /instructions/.
Only the last instruction may, and must, be an /action/.  Each
instruction is evaluated in turn until there are no instructions left.

An instruction acts on a /value stack/.  The value stack is generally
made up of /targets/, the structures which actions act upon, but may
contain other types of objects as well.

For example, the utterance ~blue bolt gust chuck~, interpreted as
~(blue bolt gust) (chuck)~, corresponds to two instructions: The first
one adds the target indicated by the /token/ with a blue bolt over a
"g" to the value stack.  The second instruction, an action, deletes
the text of the target that was put on the value stack.

*** Parametrized instructions
- ~[color] [shape] <character>~: Add the target indicated by the token
  with a hat having ~color~ and ~shape~ over ~character~ to the value
  stack.  If the color or shape are the ~default~ color or shape, they
  may be elided from the utterance.
- ~car <character>~: Add the character ~character~ to the value stack.
- ~word <word>~: Add the string ~word~ to the value stack.
- ~split <number>~: Add the window indexed ~<number>~ to the value
  stack.  This only works if you have [[https://github.com/deb0ch/emacs-winum][winum]] set up.

*** Actions
An action is an instruction that is evaluated solely for its side
effects.  It does not produce any vales for the value stack.

For documentation on actions, see the docstring of the corresponding
function in the following table.  Functions that do not act directly
on the environment will pop the top element of the value stack for its
first argument, the next one for the second argument, and so on.

|-------------+----------------------------------|
| Spoken form | Function                         |
|-------------+----------------------------------|
| select      | cursorfree-select         |
| copy        | cursorfree-copy           |
| chuck       | cursorfree-chuck          |
| bring       | cursorfree-bring          |
| move        | cursorfree-move           |
| swap        | cursorfree-swap           |
| clone       | cursorfree-clone          |
| jump        | cursorfree-jump-beginning |
| pre         | cursorfree-jump-beginning |
| post        | cursorfree-jump-end       |
| change      | cursorfree-change         |
| comment     | cursorfree-comment        |
| uncomment   | cursorfree-uncomment      |
| indent      | cursorfree-indent         |
| narrow      | cursorfree-narrow         |
| wrap        | cursorfree-wrap           |
| filler      | cursorfree-fill           |
| title       | cursorfree-capitalize     |
| upcase      | cursorfree-upcase         |
| downcase    | cursorfree-downcase       |
| crown       | cursorfree-crown          |
| center      | cursorfree-center         |
| bottom      | cursorfree-bottom         |
| pick        | cursorfree-pick           |
| fuse        | cursorfree-fuse           |
| join        | cursorfree-join           |
|-------------+----------------------------------|

*** Modifiers
A modifier is an instruction producing values for the value stack,
often but not always by modifying previous targets.

|-------------+-------------------------------------|
| Spoken form | Function                            |
|-------------+-------------------------------------|
| paint       | cursorfree-paint                    |
| leftpaint   | cursorfree-paint-left               |
| rightpaint  | cursorfree-paint-right              |
| trim        | cursorfree-trim                     |
| past        | cursorfree-past                     |
| selection   | cursorfree-current-selection        |
| inside      | cursorfree-inner-parenthesis-dwim   |
| outside     | cursorfree-outer-parenthesis-dwim   |
|-------------+-------------------------------------|

*** NOTE
The above tables are probably outdated.  For the complete and
up-to-date lists, see the definitions of ~cursorfree-actions~ and
~cursorfree-modifiers~.

** Versioning system
This project uses [[https://semver.org/][semantic versioning]].  While still on 0.y.z, an
increment of y signals breaking changes.
